In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('StockUS.csv')
df

,Name,Total Revenue Q3,Total Revenue Q2,Total Revenue PQ,Net Income Q3,Net Income Q2,Net Income PQ,Basic EPS Q3,Basic EPS Q2,Basic EPS PQ,...,ROE PQ,All High 52W,All Low 52W,RSI_Q3,RSI_Q2,RSI_PQ,Percentage Change Price Q3-Q2,Percentage Change Price Q2-PQ,Highest Price in Next Quarter,Lowest Price in Next Quarter
0,AAPL_30/03/2019,62900000,84310000,58015000,14125000,19965000,11561000,0.73,1.05,0.62,...,41.3,-18.5,34.0,67.87,28.42,61.49,-30.0,28.0,3.0,-11.0
1,AAPL_30/06/2019,84310000,58015000,53809000,19965000,11561000,10044000,1.05,0.62,0.55,...,39.7,-15.0,40.0,28.42,61.49,59.33,20.0,4.0,12.0,-5.5
2,AAPL_30/09/2019,58015000,53809000,64040000,11561000,10044000,13686000,0.62,0.55,0.76,...,58.6,-6.0,54.0,61.49,59.33,69.00,3.5,8.0,32.5,-2.5
3,AAPL_30/03/2020,64040000,91819000,58313000,13686000,22236000,11249000,0.76,1.25,0.64,...,53.6,-24.5,45.5,69.00,86.66,41.76,31.0,-14.5,49.0,-5.0
4,AAPL_30/06/2020,91819000,58313000,59685000,22236000,11249000,11253000,1.25,0.64,0.65,...,59.7,-5.0,83.0,86.66,41.76,72.41,-14.5,41.0,56.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,DXCM_30/06/2020,462800,405100,451800,92700,19900,46300,1.00,0.21,0.48,...,16.2,-10.2,175.5,66.24,58.00,66.24,21.2,44.0,18.0,-2.8
79,DXCM_30/09/2020,405100,451800,500900,19900,46300,72200,0.21,0.48,0.73,...,20.2,-12.0,179.0,58.00,66.24,52.18,43.5,3.5,5.5,-23.8
80,DXCM_30/12/2020,451800,500900,568900,46300,72200,355200,0.48,0.73,0.91,...,85.4,-22.7,95.3,66.24,52.18,51.63,3.8,-11.2,19.4,-5.0
81,DXCM_30/03/2021,500900,568900,505000,72200,355200,40300,0.73,0.91,0.33,...,8.6,-22.7,40.0,52.18,51.63,48.87,-11.0,0.0,24.5,-10.0
82,DXCM_30/06/2021,568900,505000,595100,355200,40300,62900,3.40,0.41,0.63,...,12.9,-6.0,40.5,51.63,48.87,61.12,-1.0,22.0,33.0,-3.0

In [2]:
def growth_rate_revenue_Q3_to_Q2(df):
    Q2_minus_Q3 = df['Total Revenue Q2'] - df['Total Revenue Q3']
    return abs(Q2_minus_Q3 / df['Total Revenue Q3'] if df['Total Revenue Q3'] != 0 else Q2_minus_Q3)
    
def growth_rate_revenue_Q2_to_PQ(df):
    PQ_minus_Q2 = df['Total Revenue PQ'] - df['Total Revenue Q2']
    return abs(PQ_minus_Q2 / df['Total Revenue Q2'] if df['Total Revenue Q2'] != 0 else PQ_minus_Q2)

# ///////////////////////

def growth_rate_net_income_Q3_to_Q2(df):
    Q2_minus_Q3 = df['Net Income Q2'] - df['Net Income Q3']
    return abs(Q2_minus_Q3 / df['Net Income Q3'] if df['Net Income Q3'] != 0 else Q2_minus_Q3)

def growth_rate_net_income_Q2_to_PQ(df):
    PQ_minus_Q2 = df['Net Income PQ'] - df['Net Income Q2']
    return abs(PQ_minus_Q2 / df['Net Income Q2'] if df['Net Income Q2'] != 0 else PQ_minus_Q2)

# ///////////////////////
#calculate the momentum in the change rate of financial indices reports

#calculate the absolute change rate revenue from the previous 3rd quarter to the previous 2nd quarter and
#the absolute change revenue from the previous 2nd quarter to the previous quarter and
#compare them
df['growth_rate_revenue_Q3_to_Q2'] = df.apply(growth_rate_revenue_Q3_to_Q2, axis=1)
df['growth_rate_revenue_Q2_to_PQ'] = df.apply(growth_rate_revenue_Q2_to_PQ, axis=1)
df['growth_rate_revenue_Q2PQ_compare_Q3Q2'] = abs(df['growth_rate_revenue_Q2_to_PQ'] - df['growth_rate_revenue_Q3_to_Q2'])

#calculate the absolute change net income from the previous 3rd quarter to the previous 2nd quarter and
#the absolute change net income from the previous 2nd quarter to the previous quarter and
#compare them
df['growth_rate_net_income_Q3_to_Q2'] = df.apply(growth_rate_net_income_Q3_to_Q2, axis=1)
df['growth_rate_net_income_Q2_to_PQ'] = df.apply(growth_rate_net_income_Q2_to_PQ, axis=1)
df['growth_rate_net_income_Q2PQ_compare_Q3Q2'] = abs(df['growth_rate_net_income_Q2_to_PQ'] - df['growth_rate_net_income_Q3_to_Q2'])

#calculate the absolute change EPS from the previous 3rd quarter to the previous 2nd quarter and
#the absolute change EPS from the previous 2nd quarter to the previous quarter and
#compare them
df['growth_change_EPS_Q3_to_Q2'] = abs(df['Basic EPS Q2'] - df['Basic EPS Q3'])
df['growth_change_EPS_Q2_to_PQ'] = abs(df['Basic EPS PQ'] - df['Basic EPS Q2'])
df['growth_change_EPS_Q2PQ_compare_Q3Q2'] = abs(df['growth_change_EPS_Q2_to_PQ'] - df['growth_change_EPS_Q3_to_Q2'])

#calculate the absolute change ROE from the previous 3rd quarter to the previous 2nd quarter and
#the absolute change ROE from the previous 2nd quarter to the previous quarter and
#compare them
df['growth_change_ROE_Q3_to_Q2'] = abs(df['ROE Q2'] - df['ROE Q3'])
df['growth_change_ROE_Q2_to_PQ'] = abs(df['ROE PQ'] - df['ROE Q2'])
df['growth_change_ROE_Q2PQ_compare_Q3Q2'] = abs(df['growth_change_ROE_Q2_to_PQ'] - df['growth_change_ROE_Q3_to_Q2'])

#calculate the absolute change RSI from the previous 3rd quarter to the previous 2nd quarter and
#the absolute change RSI from the previous 2nd quarter to the previous quarter and
#compare them
df['RSI_Q3Q2'] = abs(df['RSI_Q2'] - df['RSI_Q3'])
df['RSI_Q2PQ'] = abs(df['RSI_PQ'] - df['RSI_Q2'])
df['RSI_Q2PQ_Q3Q2'] = abs(df['RSI_Q3Q2'] - df['RSI_Q2PQ'])

In [3]:
#filter columns for EDA
df_out = df.drop(columns=['Name', 'Total Revenue Q3', 'Total Revenue Q2', 'Total Revenue PQ',
                         'Net Income Q3', 'Net Income Q2', 'Net Income PQ',
                         'ROE Q3', 'ROE Q2', 'ROE PQ'], axis=1)
df_out = df_out[[c for c in df_out if c not in ['Highest Price in Next Quarter', 'Lowest Price in Next Quarter']]
                + ['Highest Price in Next Quarter', 'Lowest Price in Next Quarter']]
df_out

,Basic EPS Q3,Basic EPS Q2,Basic EPS PQ,All High 52W,All Low 52W,RSI_Q3,RSI_Q2,RSI_PQ,Percentage Change Price Q3-Q2,Percentage Change Price Q2-PQ,...,growth_change_EPS_Q2_to_PQ,growth_change_EPS_Q2PQ_compare_Q3Q2,growth_change_ROE_Q3_to_Q2,growth_change_ROE_Q2_to_PQ,growth_change_ROE_Q2PQ_compare_Q3Q2,RSI_Q3Q2,RSI_Q2PQ,RSI_Q2PQ_Q3Q2,Highest Price in Next Quarter,Lowest Price in Next Quarter
0,0.73,1.05,0.62,-18.5,34.0,67.87,28.42,61.49,-30.0,28.0,...,0.43,0.11,20.1,29.7,9.6,39.45,33.07,6.38,3.0,-11.0
1,1.05,0.62,0.55,-15.0,40.0,28.42,61.49,59.33,20.0,4.0,...,0.07,0.36,29.7,1.6,28.1,33.07,2.16,30.91,12.0,-5.5
2,0.62,0.55,0.76,-6.0,54.0,61.49,59.33,69.00,3.5,8.0,...,0.21,0.14,1.6,18.9,17.3,2.16,9.67,7.51,32.5,-2.5
3,0.76,1.25,0.64,-24.5,45.5,69.00,86.66,41.76,31.0,-14.5,...,0.61,0.12,40.2,45.2,5.0,17.66,44.90,27.24,49.0,-5.0
4,1.25,0.64,0.65,-5.0,83.0,86.66,41.76,72.41,-14.5,41.0,...,0.01,0.60,45.2,6.1,39.1,44.90,30.65,14.25,56.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,1.00,0.21,0.48,-10.2,175.5,66.24,58.00,66.24,21.2,44.0,...,0.27,0.52,36.2,7.4,28.8,8.24,8.24,0.00,18.0,-2.8
79,0.21,0.48,0.73,-12.0,179.0,58.00,66.24,52.18,43.5,3.5,...,0.25,0.02,7.4,4.0,3.4,8.24,14.06,5.82,5.5,-23.8
80,0.48,0.73,0.91,-22.7,95.3,66.24,52.18,51.63,3.8,-11.2,...,0.18,0.07,4.0,65.2,61.2,14.06,0.55,13.51,19.4,-5.0
81,0.73,0.91,0.33,-22.7,40.0,52.18,51.63,48.87,-11.0,0.0,...,0.58,0.40,65.2,76.8,11.6,0.55,2.76,2.21,24.5,-10.0
82,3.40,0.41,0.63,-6.0,40.5,51.63,48.87,61.12,-1.0,22.0,...,0.22,2.77,76.8,4.3,72.5,2.76,12.25,9.49,33.0,-3.0

In [4]:
df_out.to_csv('stock_us_cleaned.csv', index=False)